# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imagedraw.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from dots import Dots
import sys,os
import cv2
import numpy as np
from PIL import Image

np.set_printoptions(threshold=np.inf)

def analyze(path, value):
    im_array = np.array(Image.open(path).convert("L"))
    countblack, countwhite = 0, 0
    for i in range(im_array.size):
        pixel = im_array.flat[i]
        if pixel < 180:
            countblack += 1
        else:
            countwhite += 1
    if value == 0:
        percentage = 100 * countblack / (countblack + countwhite)
    elif value == 1:
        percentage = 100 * countwhite / (countblack + countwhite)
    return percentage,countwhite,countblack

class Image_manipulate(object):
    def __init__(self,path):
        self.path= path
        self.image=cv2.imdecode(np.fromfile(self.path, dtype=np.uint8), -1)
    def gray(self):
        gray=cv2.cvtColor(self.image, cv2.COLOR_BGR2GRAY)
        cv2.imencode(self.path[-4:], gray)[1].tofile(os.path.join(os.path.dirname(self.path),'Gray'+self.path[-4:]))
        graypath=os.path.join(os.path.dirname(self.path),'Gray'+self.path[-4:])
        graypath=os.path.abspath(graypath)
        return graypath
    def blur(self,value,blurnum1,blurnum2,blurnum3):
        if value==1:
            blur_img=cv2.blur(self.image,(int(blurnum1),int(blurnum2)))
        if value==2:
            blur_img = cv2.GaussianBlur(self.image, (int(blurnum1), int(blurnum2)),0)
        if value==3:
            blur_img = cv2.medianBlur(self.image, int(blurnum1))
        if value==4:
            blur_img = cv2.bilateralFilter(self.image, int(blurnum1), int(blurnum2),int(blurnum3))
        cv2.imencode(self.path[-4:], blur_img)[1].tofile(os.path.join(os.path.dirname(self.path), 'Blurred' + self.path[-4:]))
        blur_path = os.path.join(os.path.dirname(self.path), 'Blurred' + self.path[-4:])
        blur_path = os.path.abspath(blur_path)
        return blur_path
    def binary(self,blacknum):
        _,thresh=cv2.threshold(self.image,int(blacknum),255,cv2.THRESH_BINARY)
        cv2.imencode(self.path[-4:], thresh)[1].tofile(
            os.path.join(os.path.dirname(self.path), 'Threshold' + self.path[-4:]))
        thresh_path = os.path.join(os.path.dirname(self.path), 'Threshold' + self.path[-4:])
        thresh_path=os.path.abspath(thresh_path)
        return thresh_path
    def openandclose(self,value,kernel1):
        kernel=np.ones((int(kernel1),int(kernel1)),np.uint8)
        if value==1:
            opened=cv2.morphologyEx(self.image,cv2.MORPH_OPEN,kernel)
            cv2.imencode(self.path[-4:], opened)[1].tofile(
                os.path.join(os.path.dirname(self.path), 'Open Morph' + self.path[-4:]))
            open_path = os.path.join(os.path.dirname(self.path), 'Open Morph' + self.path[-4:])
            path=os.path.abspath(open_path)
        if value==2:
            closed = cv2.morphologyEx(self.image, cv2.MORPH_CLOSE, kernel)
            cv2.imencode(self.path[-4:], closed)[1].tofile(
                os.path.join(os.path.dirname(self.path), 'Close Morph' + self.path[-4:]))
            closed_path = os.path.join(os.path.dirname(self.path), 'Close Morph' + self.path[-4:])
            path=os.path.abspath(closed_path)
        return path
    def erode_dilate(self,value,kernel1,iteration):
        kernel = np.ones((int(kernel1), int(kernel1)), np.uint8)
        iteration=int(iteration)
        if value==1:
            erosion=cv2.erode(self.image,kernel,iterations=iteration)
            cv2.imencode(self.path[-4:], erosion)[1].tofile(
                os.path.join(os.path.dirname(self.path), 'Erode' + self.path[-4:]))
            erode_path = os.path.join(os.path.dirname(self.path), 'Erode' + self.path[-4:])
            path = os.path.abspath(erode_path)
        if value==2:
            dilation=cv2.dilate(self.image,kernel,iterations=iteration)
            cv2.imencode(self.path[-4:], dilation)[1].tofile(
                os.path.join(os.path.dirname(self.path), 'Dilate' + self.path[-4:]))
            dilate_path = os.path.join(os.path.dirname(self.path), 'Dilate' + self.path[-4:])
            path = os.path.abspath(dilate_path)
        return path
    def brim_find(self,search,approximate):
        search_list=[cv2.RETR_EXTERNAL,cv2.RETR_LIST,cv2.RETR_CCOMP,cv2.RETR_TREE]
        approximate_list=[cv2.CHAIN_APPROX_NONE,cv2.CHAIN_APPROX_SIMPLE]
        img,dot,index=cv2.findContours(self.image,search_list[search],approximate_list[approximate])
        return dot,index
    def brim_draw(self,dot,index,color,width):
        color_list = [(0, 0, 255), (0, 255, 0), (255, 0, 0)]
        drawcontours = cv2.drawContours(self.image.copy(),dot,int(index),color_list[color],int(width))
        cv2.imencode(self.path[-4:], drawcontours)[1].tofile(
            os.path.join(os.path.dirname(self.path), 'Contours' + self.path[-4:]))
        brim_path = os.path.join(os.path.dirname(self.path), 'Contours' + self.path[-4:])
        brim_path=os.path.abspath(brim_path)
        return brim_path

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1023, 837)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, -1, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem)
        self.lineEdit_11 = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_11.setReadOnly(True)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_6.addWidget(self.lineEdit_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_6.addItem(spacerItem1)
        self.verticalLayout_6.setStretch(0, 8)
        self.verticalLayout_6.setStretch(2, 8)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.pushButton = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 11)
        self.horizontalLayout.setStretch(2, 1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_2.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout.addWidget(self.graphicsView)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtWidgets.QToolBox(Dialog)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 328, 591))
        self.page.setObjectName("page")
        self.frame = QtWidgets.QFrame(self.page)
        self.frame.setGeometry(QtCore.QRect(10, 0, 301, 41))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.frame_3 = QtWidgets.QFrame(self.page)
        self.frame_3.setGeometry(QtCore.QRect(10, 50, 301, 301))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_3.setObjectName("frame_3")
        self.radioButton = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton.setGeometry(QtCore.QRect(110, 100, 91, 16))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_2.setGeometry(QtCore.QRect(200, 100, 91, 16))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_3.setGeometry(QtCore.QRect(110, 130, 81, 16))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_4.setGeometry(QtCore.QRect(210, 200, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_4.setGeometry(QtCore.QRect(200, 130, 101, 16))
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_3.setGeometry(QtCore.QRect(100, 40, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 91, 16))
        self.label_5.setObjectName("label_5")
        self.label_21 = QtWidgets.QLabel(self.frame_3)
        self.label_21.setGeometry(QtCore.QRect(10, 10, 171, 21))
        self.label_21.setObjectName("label_21")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(200, 10, 51, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.frame_13 = QtWidgets.QFrame(self.frame_3)
        self.frame_13.setGeometry(QtCore.QRect(20, 170, 151, 61))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_17.setGeometry(QtCore.QRect(10, 30, 21, 20))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.label_33 = QtWidgets.QLabel(self.frame_13)
        self.label_33.setGeometry(QtCore.QRect(0, 10, 101, 16))
        self.label_33.setObjectName("label_33")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_18.setGeometry(QtCore.QRect(90, 30, 31, 20))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.frame_13)
        self.lineEdit_19.setGeometry(QtCore.QRect(50, 30, 31, 20))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_34 = QtWidgets.QLabel(self.frame_13)
        self.label_34.setGeometry(QtCore.QRect(77, 30, 16, 21))
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.frame_13)
        self.label_35.setGeometry(QtCore.QRect(30, 30, 20, 21))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.frame_11 = QtWidgets.QFrame(self.frame_3)
        self.frame_11.setGeometry(QtCore.QRect(20, 170, 151, 61))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit.setGeometry(QtCore.QRect(40, 30, 31, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_11)
        self.lineEdit_2.setGeometry(QtCore.QRect(90, 30, 31, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_7 = QtWidgets.QLabel(self.frame_11)
        self.label_7.setGeometry(QtCore.QRect(0, 10, 141, 16))
        self.label_7.setObjectName("label_7")
        self.label_6 = QtWidgets.QLabel(self.frame_11)
        self.label_6.setGeometry(QtCore.QRect(70, 30, 21, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_3)
        self.frame_12.setGeometry(QtCore.QRect(20, 170, 151, 61))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_12)
        self.lineEdit_15.setGeometry(QtCore.QRect(40, 30, 31, 20))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.label_31 = QtWidgets.QLabel(self.frame_12)
        self.label_31.setGeometry(QtCore.QRect(0, 10, 101, 16))
        self.label_31.setObjectName("label_31")
        self.toolBox.addItem(self.page, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 328, 591))
        self.page_4.setObjectName("page_4")
        self.frame_2 = QtWidgets.QFrame(self.page_4)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 321, 281))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame_2.setObjectName("frame_2")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(10, 10, 221, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(80, 60, 101, 21))
        self.label_9.setObjectName("label_9")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 60, 31, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_5.setGeometry(QtCore.QRect(120, 100, 75, 23))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(10, 140, 231, 16))
        self.label_10.setObjectName("label_10")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_5.setGeometry(QtCore.QRect(190, 30, 31, 20))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_12 = QtWidgets.QLabel(self.frame_2)
        self.label_12.setGeometry(QtCore.QRect(80, 30, 101, 21))
        self.label_12.setObjectName("label_12")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setGeometry(QtCore.QRect(190, 160, 31, 20))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_14 = QtWidgets.QLabel(self.frame_2)
        self.label_14.setGeometry(QtCore.QRect(80, 160, 101, 21))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_8.setGeometry(QtCore.QRect(190, 190, 31, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_15 = QtWidgets.QLabel(self.frame_2)
        self.label_15.setGeometry(QtCore.QRect(80, 190, 101, 21))
        self.label_15.setObjectName("label_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_6.setGeometry(QtCore.QRect(130, 230, 75, 23))
        self.pushButton_6.setObjectName("pushButton_6")
        self.toolBox.addItem(self.page_4, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 328, 591))
        self.page_3.setObjectName("page_3")
        self.frame_4 = QtWidgets.QFrame(self.page_3)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 311, 221))
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_4.setObjectName("frame_4")
        self.label_16 = QtWidgets.QLabel(self.frame_4)
        self.label_16.setGeometry(QtCore.QRect(10, 60, 221, 21))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.frame_4)
        self.label_17.setGeometry(QtCore.QRect(10, 10, 111, 21))
        self.label_17.setObjectName("label_17")
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_7.setGeometry(QtCore.QRect(230, 60, 75, 23))
        self.pushButton_7.setObjectName("pushButton_7")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_4)
        self.lineEdit_10.setGeometry(QtCore.QRect(140, 10, 31, 20))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_19 = QtWidgets.QLabel(self.frame_4)
        self.label_19.setGeometry(QtCore.QRect(10, 110, 211, 21))
        self.label_19.setObjectName("label_19")
        self.pushButton_8 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_8.setGeometry(QtCore.QRect(230, 110, 75, 23))
        self.pushButton_8.setObjectName("pushButton_8")
        self.toolBox.addItem(self.page_3, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setGeometry(QtCore.QRect(0, 0, 328, 591))
        self.page_5.setObjectName("page_5")
        self.frame_5 = QtWidgets.QFrame(self.page_5)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 321, 461))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_5.setObjectName("frame_5")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setGeometry(QtCore.QRect(10, 10, 301, 161))
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.label_20 = QtWidgets.QLabel(self.frame_6)
        self.label_20.setGeometry(QtCore.QRect(10, 10, 111, 16))
        self.label_20.setObjectName("label_20")
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_5.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_6.setGeometry(QtCore.QRect(10, 70, 261, 21))
        self.radioButton_6.setObjectName("radioButton_6")
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_7.setGeometry(QtCore.QRect(10, 100, 241, 21))
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_8.setGeometry(QtCore.QRect(10, 130, 191, 21))
        self.radioButton_8.setObjectName("radioButton_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_5)
        self.frame_7.setGeometry(QtCore.QRect(10, 190, 301, 131))
        self.frame_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_7.setObjectName("frame_7")
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        self.label_22.setGeometry(QtCore.QRect(10, 10, 281, 16))
        self.label_22.setObjectName("label_22")
        self.radioButton_13 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_13.setGeometry(QtCore.QRect(10, 40, 271, 21))
        self.radioButton_13.setObjectName("radioButton_13")
        self.radioButton_14 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_14.setGeometry(QtCore.QRect(10, 70, 281, 41))
        self.radioButton_14.setObjectName("radioButton_14")
        self.pushButton_10 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_10.setGeometry(QtCore.QRect(130, 530, 75, 23))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_9 = QtWidgets.QPushButton(self.page_5)
        self.pushButton_9.setGeometry(QtCore.QRect(120, 340, 75, 23))
        self.pushButton_9.setObjectName("pushButton_9")
        self.frame_9 = QtWidgets.QFrame(self.page_5)
        self.frame_9.setGeometry(QtCore.QRect(10, 460, 301, 61))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.label_26 = QtWidgets.QLabel(self.frame_9)
        self.label_26.setGeometry(QtCore.QRect(160, 20, 71, 21))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.frame_9)
        self.label_27.setGeometry(QtCore.QRect(10, 20, 91, 21))
        self.label_27.setObjectName("label_27")
        self.comboBox = QtWidgets.QComboBox(self.frame_9)
        self.comboBox.setGeometry(QtCore.QRect(110, 20, 41, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_9)
        self.comboBox_2.setGeometry(QtCore.QRect(240, 20, 41, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.frame_8 = QtWidgets.QFrame(self.page_5)
        self.frame_8.setGeometry(QtCore.QRect(10, 380, 301, 61))
        self.frame_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_8.setObjectName("frame_8")
        self.label_24 = QtWidgets.QLabel(self.frame_8)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 211, 16))
        self.label_24.setObjectName("label_24")
        self.radioButton_17 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_17.setGeometry(QtCore.QRect(10, 30, 61, 21))
        self.radioButton_17.setObjectName("radioButton_17")
        self.radioButton_18 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_18.setGeometry(QtCore.QRect(130, 30, 81, 21))
        self.radioButton_18.setObjectName("radioButton_18")
        self.radioButton_19 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_19.setGeometry(QtCore.QRect(230, 30, 61, 21))
        self.radioButton_19.setObjectName("radioButton_19")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setGeometry(QtCore.QRect(0, 0, 328, 591))
        self.page_6.setObjectName("page_6")
        self.frame_10 = QtWidgets.QFrame(self.page_6)
        self.frame_10.setGeometry(QtCore.QRect(10, 0, 301, 551))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.label_25 = QtWidgets.QLabel(self.frame_10)
        self.label_25.setGeometry(QtCore.QRect(20, 120, 261, 231))
        self.label_25.setText("")
        self.label_25.setScaledContents(True)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.frame_14 = QtWidgets.QFrame(self.frame_10)
        self.frame_14.setGeometry(QtCore.QRect(0, 10, 301, 71))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_14.setObjectName("frame_14")
        self.label_28 = QtWidgets.QLabel(self.frame_14)
        self.label_28.setGeometry(QtCore.QRect(10, 10, 171, 21))
        self.label_28.setObjectName("label_28")
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_9.setGeometry(QtCore.QRect(50, 40, 71, 21))
        self.radioButton_9.setObjectName("radioButton_9")
        self.radioButton_10 = QtWidgets.QRadioButton(self.frame_14)
        self.radioButton_10.setGeometry(QtCore.QRect(160, 40, 71, 21))
        self.radioButton_10.setObjectName("radioButton_10")
        self.pushButton_12 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_12.setGeometry(QtCore.QRect(110, 90, 75, 23))
        self.pushButton_12.setObjectName("pushButton_12")
        self.toolBox.addItem(self.page_6, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.setStretch(0, 2)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.setStretch(0, 1)
        self.verticalLayout_2.setStretch(1, 100)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)

        self.retranslateUi(Dialog)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(7)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Get Boundary"))
        self.label.setText(_translate("Dialog", "Image path："))
        self.pushButton.setText(_translate("Dialog", "Choose"))
        self.label_2.setText(_translate("Dialog", "Thumbnail:"))
        self.pushButton_2.setText(_translate("Dialog", "Gray"))
        self.radioButton.setText(_translate("Dialog", "Average"))
        self.radioButton_2.setText(_translate("Dialog", "Gaussian"))
        self.radioButton_3.setText(_translate("Dialog", "Median"))
        self.pushButton_4.setText(_translate("Dialog", "Blur"))
        self.radioButton_4.setText(_translate("Dialog", "Bilateral"))
        self.pushButton_3.setText(_translate("Dialog", "Threshold"))
        self.label_5.setText(_translate("Dialog", "Blur Type："))
        self.label_21.setText(_translate("Dialog", "Threshold Parameter："))
        self.lineEdit_17.setText(_translate("Dialog", "9"))
        self.label_33.setText(_translate("Dialog", "Parameter："))
        self.lineEdit_18.setText(_translate("Dialog", "9"))
        self.lineEdit_19.setText(_translate("Dialog", "9"))
        self.label_34.setText(_translate("Dialog", "X"))
        self.label_35.setText(_translate("Dialog", "X"))
        self.lineEdit.setText(_translate("Dialog", "9"))
        self.lineEdit_2.setText(_translate("Dialog", "9"))
        self.label_7.setText(_translate("Dialog", "Convolution Size:"))
        self.label_6.setText(_translate("Dialog", "X"))
        self.lineEdit_15.setText(_translate("Dialog", "9"))
        self.label_31.setText(_translate("Dialog", "Kernel Size："))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("Dialog", "Gray,Threshold,Blur"))
        self.label_8.setText(_translate("Dialog", "Erode:"))
        self.label_9.setText(_translate("Dialog", "Iteration："))
        self.lineEdit_3.setText(_translate("Dialog", "4"))
        self.pushButton_5.setText(_translate("Dialog", "Erode"))
        self.label_10.setText(_translate("Dialog", "Dilate:"))
        self.lineEdit_5.setText(_translate("Dialog", "5"))
        self.label_12.setText(_translate("Dialog", "Kernel Size:"))
        self.lineEdit_7.setText(_translate("Dialog", "5"))
        self.label_14.setText(_translate("Dialog", "Kernel Size："))
        self.lineEdit_8.setText(_translate("Dialog", "4"))
        self.label_15.setText(_translate("Dialog", "Iteration："))
        self.pushButton_6.setText(_translate("Dialog", "Dilate"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("Dialog", "Erode and Dilate"))
        self.label_16.setText(_translate("Dialog", "Open Morph:Clear the noise"))
        self.label_17.setText(_translate("Dialog", "Kernel Size："))
        self.pushButton_7.setText(_translate("Dialog", "Open"))
        self.lineEdit_10.setText(_translate("Dialog", "9"))
        self.label_19.setText(_translate("Dialog", "Close Morph:Fill the inner"))
        self.pushButton_8.setText(_translate("Dialog", "Close"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("Dialog", "Open Morph and Close Morph"))
        self.label_20.setText(_translate("Dialog", "Search Typr："))
        self.radioButton_5.setText(_translate("Dialog", "Only External"))
        self.radioButton_6.setText(_translate("Dialog", "List(No hierarchy)"))
        self.radioButton_7.setText(_translate("Dialog", "Two-level hierarchy"))
        self.radioButton_8.setText(_translate("Dialog", "Full hierarchy"))
        self.label_22.setText(_translate("Dialog", "Contour approximation method："))
        self.radioButton_13.setText(_translate("Dialog", "Store all the contour points"))
        self.radioButton_14.setText(_translate("Dialog", "Compress all directions and \n"
"leave only end points"))
        self.pushButton_10.setText(_translate("Dialog", "Execute"))
        self.pushButton_9.setText(_translate("Dialog", "Execute"))
        self.label_26.setText(_translate("Dialog", "Contour："))
        self.label_27.setText(_translate("Dialog", "Line width："))
        self.comboBox.setItemText(0, _translate("Dialog", "1"))
        self.comboBox.setItemText(1, _translate("Dialog", "2"))
        self.comboBox.setItemText(2, _translate("Dialog", "3"))
        self.comboBox.setItemText(3, _translate("Dialog", "4"))
        self.comboBox.setItemText(4, _translate("Dialog", "5"))
        self.label_24.setText(_translate("Dialog", "Contours color："))
        self.radioButton_17.setText(_translate("Dialog", "red"))
        self.radioButton_18.setText(_translate("Dialog", "green"))
        self.radioButton_19.setText(_translate("Dialog", "blue"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("Dialog", "Get Contour"))
        self.label_28.setText(_translate("Dialog", "Color："))
        self.radioButton_9.setText(_translate("Dialog", "black"))
        self.radioButton_10.setText(_translate("Dialog", "white"))
        self.pushButton_12.setText(_translate("Dialog", "Execute"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("Dialog", "Get Pixel Information"))

        Dialog.setWindowFlags(QtCore.Qt.WindowMinMaxButtonsHint | QtCore.Qt.WindowCloseButtonHint)
        self.pushButton.clicked.connect(self.chooseimg)
        self.pushButton_2.clicked.connect(self.graybutton)
        self.radioButton.toggle()
        self.frame_12.hide()
        self.frame_13.hide()
        self.radioButton.toggled.connect(self.toggle1and2)
        self.radioButton_2.toggled.connect(self.toggle1and2)
        self.radioButton_3.toggled.connect(self.toggle3)
        self.radioButton_4.toggled.connect(self.toggle4)
        self.pushButton_3.clicked.connect(self.binarybutton)
        self.pushButton_4.clicked.connect(self.blurbutton)
        self.pushButton_7.clicked.connect(self.openbutton)
        self.pushButton_8.clicked.connect(self.closebutton)
        self.pushButton_5.clicked.connect(self.erodebutton)
        self.pushButton_6.clicked.connect(self.dilatebutton)
        self.pushButton_9.clicked.connect(self.brim_findbutton)
        self.pushButton_10.clicked.connect(self.brim_drawburron)
        self.pushButton_12.clicked.connect(self.analyze_button)
        self.radioButton_6.toggle()
        self.radioButton_14.toggle()
        self.radioButton_17.toggle()
        self.radioButton_9.toggle()

    def toggle1and2(self):
        self.frame_12.hide()
        self.frame_13.hide()
        self.frame_11.show()
    def toggle3(self):
        self.frame_11.hide()
        self.frame_13.hide()
        self.frame_12.show()
    def toggle4(self):
        self.frame_13.show()
        self.frame_11.hide()
        self.frame_12.hide()


    def chooseimg(self):
        self.path, self.filetype = QtWidgets.QFileDialog.getOpenFileName(directory="D:/",
                                                                         filter="Image Files (*.jpg)(*.jpeg)(*.png);;"
                                                                                "Bmp Files (*.bmp);;"
                                                                                "Raw Files (*.raw);;")
        self.lineEdit_11.setText(self.path)
        img=QtGui.QPixmap(self.path)
        self.img_size=img.size()
        if img.width()<=img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else :
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene=QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()

    def graybutton(self):
        gray_init=Image_manipulate(self.path)
        graypath=gray_init.gray()
        img = QtGui.QPixmap(graypath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(graypath)
    def binarybutton(self):
        blacknum=self.lineEdit_12.text()
        path=self.lineEdit_11.text()
        black_init=Image_manipulate(path)
        blackpath=black_init.binary(int(blacknum))
        img= QtGui.QPixmap(blackpath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(blackpath)
    def blurbutton(self):
        path=self.lineEdit_11.text()
        blur_init=Image_manipulate(path)
        if self.radioButton.isChecked():
            blurpath=blur_init.blur(1,self.lineEdit.text(),self.lineEdit_2.text(),0)
        if self.radioButton_2.isChecked():
            blurpath=blur_init.blur(2,self.lineEdit.text(),self.lineEdit_2.text(),0)
        if self.radioButton_3.isChecked():
            blurpath=blur_init.blur(3,self.lineEdit_15.text(),0,0)
        if self.radioButton_4.isChecked():
            blurpath=blur_init.blur(4,self.lineEdit_17.text(),self.lineEdit_19.text(),self.lineEdit_18.text())
        img= QtGui.QPixmap(blurpath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(blurpath)
    def openbutton(self):
        path = self.lineEdit_11.text()
        kernelnum1=self.lineEdit_10.text()
        open_=Image_manipulate(path)
        openpath=open_.openandclose(1,kernelnum1)
        img= QtGui.QPixmap(openpath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(openpath)
    def closebutton(self):
        path = self.lineEdit_11.text()
        kernelnum1=self.lineEdit_10.text()
        close_=Image_manipulate(path)
        closepath=close_.openandclose(2,kernelnum1)
        img= QtGui.QPixmap(closepath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(closepath)
    def erodebutton(self):
        path = self.lineEdit_11.text()
        kernelnum1, iteration=self.lineEdit_5.text(),self.lineEdit_3.text()
        erode=Image_manipulate(path)
        erodepath=erode.erode_dilate(1,kernelnum1,iteration)
        img = QtGui.QPixmap(erodepath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(erodepath)
    def dilatebutton(self):
        path = self.lineEdit_11.text()
        kernelnum1,iteration=self.lineEdit_7.text(),self.lineEdit_8.text()
        dilate=Image_manipulate(path)
        dilatepath=dilate.erode_dilate(2,kernelnum1,iteration)
        img = QtGui.QPixmap(dilatepath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(dilatepath)
    def brim_findbutton(self):
        path = self.lineEdit_11.text()
        s_method, a_method=0,0
        if self.radioButton_5.isChecked():
            s_method=0
        elif self.radioButton_6.isChecked():
            s_method=1
        elif self.radioButton_7.isChecked():
            s_method=2
        elif self.radioButton_8.isChecked():
            s_method=3
        if self.radioButton_13.isChecked():
            a_method=0
        if self.radioButton_14.isChecked():
            a_method=1
        brim_find=Image_manipulate(path)
        self.dots,index=brim_find.brim_find(s_method,a_method)
        self.comboBox_2.clear()
        self.comboBox_2.addItem('-1')
        for i in range(int(index.size/4)):
            self.comboBox_2.addItem(str(i))
    def brim_drawburron(self):
        color = 0
        if self.radioButton_17.isChecked():
            color=0
        if self.radioButton_18.isChecked():
            color=1
        if self.radioButton_19.isChecked():
            color=2
        width,index=self.comboBox.currentText(),self.comboBox_2.currentText()

        brim_draw = Image_manipulate(self.path)
        brimpath=brim_draw.brim_draw(self.dots,index,color,width)
        img = QtGui.QPixmap(brimpath)
        if img.width() <= img.height():
            img = img.scaledToHeight(self.graphicsView.height())
        else:
            img = img.scaledToWidth(self.graphicsView.width())
        graphicscene = QtWidgets.QGraphicsScene()
        graphicscene.addPixmap(img)
        self.graphicsView.setScene(graphicscene)
        self.graphicsView.show()
        self.lineEdit_11.setText(brimpath)

        window = QtWidgets.QDialog()
        ui = Dots()
        ui.setupUi(window,self.dots[int(index)],str(self.img_size)[18:])
        window.exec_()
    def analyze_button(self):
        path = self.lineEdit_11.text()
        value=0
        if self.radioButton_9.isChecked():
            value=0
        else:
            value=1
        per,white,black=analyze(path,value)
        self.label_25.setText("Percentage of the choosed color：\n{:.4f}%\nThe number of white pixel：\n{}\nThe number of all the pixel：\n{}".format(per,white,black))



if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())